# Generated by Django 3.2.7 on 2023-02-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='shortenedValue',
            new_name='shortened_value',
        ),
        migrations.AddField(
            model_name='url',
            name='number_of_clicks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
